# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Holdem Trainer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Holdem Trainer
  pod 'SnapKit', '~> 5.0.0'
  pod 'GRDB.swift'
  pod 'SwiftLint'

end
